import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 
    <html lang="en">
      
      <body className="bg-slate-900">

      <Image className=""
        alt={"Background Image"}
        src="/bg.jpg"
        sizes="100vw"
        layout="fill"
        style={{ zIndex: -1 }}
      />
      
  
        {children}
        </body>
    </html>
 
  );
}
